### ISSUE TITLE
how to use more than one select box

### ISSUE THREAD

**Issue by kapilkarda** [domiSchenk/ionic-Select-Control#1]
Hello
This is nice but i am unable to use more than one select box in a single controller can you help me.

Thanks in advance.

**Comment by cleytonferrari** [comment]
Hello
Help me too

**Comment by kapilkarda** [comment]
Hello,

I think this gonna be help you please have a link.
http://codepen.io/Auro/pen/wKpdn

Thanks

**Comment by cleytonferrari** [comment]
Thank @kapilkarda helped me a lot! I made a Pull Request https://github.com/domiSchenk/ionic-Select-Control/pull/3

**Comment by kapilkarda** [comment]
my pleasure @cleytonferrari .
