### ISSUE TITLE
how i can set a default selected value ??

### ISSUE THREAD

**Issue by hatimox** [domiSchenk/ionic-Select-Control#8]

**Comment by domiSchenk** [comment]
Currently there is no method to set the default value,
but you can set $scope.selectedValue and $scope.selectedId in your code.

**Comment by ManivannanP** [comment]
Even i set $scope.selectedValue and $scope.selectedId also its not binding.

**Comment by domiSchenk** [comment]
Did you add the binding in the HTML code?
 see here: http://codepen.io/Auro/pen/cvDkt?editors=1010
